main/urls.py
from django.urls import path
from main.views import BweightView,SignUpView,SignInView
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from main import forms

app_name='main'
urlpatterns = [

    path('', TemplateView.as_view(template_name='main/home.html'),name='home'),
    path('weight/',BweightView.as_view(),name='weight'),
    path('login/',SignInView.as_view(),name="login",),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',SignUpView.as_view(),name='signup'),
]

main/models.py
from django.db import models
from users.models import CustomUser

class BodyWeight(models.Model):
    weight = models.PositiveIntegerField()
    date = models.DateField()
    owner = models.ForeignKey(CustomUser,models.CASCADE)

main/forms.py
from django.forms import ModelForm
from django import forms
from main.models import BodyWeight
from django.contrib.auth import authenticate

class BodyWeightForm(ModelForm):
    class Meta:
        model = BodyWeight
        fields = ['weight',]

class AuthenticationForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'Email'}))
    password = forms.CharField(strip=False,widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

    def __init__(self,request=None,*args,**kwargs):
        self.request =request
        self.user = None
        super().__init__(*args,**kwargs)

    def clean(self):
        email =self.cleaned_data.get("email")
        password =self.cleaned_data.get("password")
        if email is not None and password:
            self.user = authenticate(self.request,email=email,password=password)
            if self.user is None:
                raise forms.ValidationError("Invalid Email/Password combination.")
        return self.cleaned_data

    def get_user(self):
        return self.user

main/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from main.forms import BodyWeightForm
from main.models import BodyWeight
from django.contrib.auth import login,authenticate
from django.contrib import messages
from django.views.generic import FormView
from django.contrib.auth.views import LoginView
from users.forms import CustomUserCreationForm
from django.db import IntegrityError
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import CustomUser
from datetime import datetime
from main.forms import AuthenticationForm


class BweightView(LoginRequiredMixin,View):
    

    def datalist(self,model):
        """
        Accepts a model as arguement and returns a list of dictionary with the date formated
        """
        calender = {1:'Jan',2:'Feb',3:'Mar',4:'Apr',5:'May',6:'Jun',7:'Jul',8:'Aug',9:'Sep',10:'Oct',11:'Nov',12:'Dec'}
        data = model.objects.filter(owner=self.request.user).values().order_by('date')
        a= 0
        d= []
       
        for i in data:
            g={}
            for j in i:
                if j=='date':
                   
                    d_obj = i[j]
                    d_day = d_obj.day
                    d_month = calender[d_obj.month]
                    d_year = d_obj.year
                    g['label'] =str(d_month)+' '+str(d_day)+', '+str(d_year)
                   
                elif j=='weight':
                    w_obj = i[j]
                    g['y'] = w_obj
           
            d.append(g)

       
       
        return d

    def get(self,request,*args,**kwargs):
        context = {'form':BodyWeightForm(),'data':self.datalist(BodyWeight)}
        return render(request,'main/chart.html',context)

    def post(self,request, *args, **kwargs):
        form = BodyWeightForm(request.POST)
        objs = BodyWeight.objects.filter(owner=request.user).values()
        today = datetime.today().strftime('%Y-%m-%d')
        today = today.split('-')
        if form.is_valid():
                bweight = form.save(commit=False)
                if objs:
                    for i in objs:
                        model_date = i['date']
                        if model_date.year == int(today[0]) and model_date.month == int(today[1]) and model_date.day==int(today[2]):
                            try:
                                a = 9/0
                            except ZeroDivisionError:
                                messages.warning(request,'Sorry,you have entered your weight for the day.')
                            finally:         
                                return HttpResponseRedirect(reverse_lazy('main:weight'))
                bweight.owner = request.user
                today = datetime.today().strftime('%Y-%m-%d')
                bweight.date = today
                bweight.save()        
                return HttpResponseRedirect(reverse_lazy('main:weight'))
        return render(request,'main/chart.html',{'form':form,'data':self.datalist(BodyWeight)})

class SignUpView(FormView):
    template_name = "main/signup_signin.html"
    form_class=CustomUserCreationForm
    
    def get_success_url(self):
        redirect_to =self.request.GET.get("next","/")
        return redirect_to
    def form_valid(self,form):
        response = super().form_valid(form)
        form.save()
        email = form.cleaned_data.get("email")
        raw_password = form.cleaned_data.get("password1")
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        birth_date = form.cleaned_data.get("birth_date")
        gender= form.cleaned_data.get("gender")
        user =authenticate(email=email,password=raw_password,first_name=first_name,last_name=last_name,birth_date=birth_date,gender=gender)
        login(self.request,user)
        form.send_mail()
        messages.info(self.request,"You signed up successfully")
        return response

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        sign_in_form = AuthenticationForm()
        context['sign_in_form'] =sign_in_form
        return context
        

class SignInView(LoginView):
    template_name= "main/signup_signin.html"
    form_class = AuthenticationForm

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        sign_up_form = CustomUserCreationForm()
        context['sign_up_form'] = sign_up_form
        return context

main/templates/accounts/password_change.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style type="text/css">
        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .h3 {
            text-align: center;
        }
    </style>

</head>

<body>
    <form id="id_password_change_form" method="POST" class="form-signin">{% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Change password</h1>
        <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password"
            required="true">
        <input name="new_password1" class="form-control" placeholder="New password" type="password"
            id="id_new_password1" required="true">
        <input name="new_password2" class="form-control" placeholder="Confirm password" type="password"
            id="id_new_password2" required="true">

        {% for field in form %}
        {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% endfor %}

        <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
    </form>
</body>

</html>

main/templates/accounts/password_change_done.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <div class="d-flex flex-column">
            <p class="m-auto">Your password has been Updated.</p>
        </div>
    </div>
</body>

</html>

main/templates/accounts/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <div class="d-flex flex-column">
            <p class="m-auto">Your password has been reset. You may go ahead and <a href="{% url 'main:login' %}">sign
                    in</a>
                now.
            </p>
        </div>
    </div>
</body>

</html>

main/templates/accounts/password_reset_confirm.html
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">submit</button>
</form>

main/templates/accounts/password_reset_done.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">

        <div class="d-flex flex-column">
            <p class="m-auto p-2">
                We've emailed you instructions for setting your password, if an account exists with the email you
                entered.
                You should receive them shortly.
            </p>
            <p class="m-auto p-2">
                If you don't receive an email, please make sure you've entered the address you registered with,
                and check your spam folder.
            </p>
            <p class="m-auto p-2"><a href="{% url 'main:home' %}">Return to home page</a></p>
        </div>
    </div>
</body>

</html>

main/templates/accounts/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Weight-Tracker Team
{% endautoescape %}

main/templates/accounts/password_reset_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style type="text/css">
        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: 10px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .h3 {
            text-align: center;
        }
    </style>
</head>

<body>
    <form id="id_password_reset_form" method="POST" class="form-signin">{% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Reset password</h1>
        <input name="email" class="form-control" placeholder="Email address" type="email" id="id_email" required="true">
        <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block">Send reset email</button>
    </form>
</body>

</html>

main/templates/main/chart.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Bar Chart Template | PrepBootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <link rel="stylesheet" href="{% static 'css/style1.css' %}" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">

    <!-- Custom Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style1.css' %}" />

    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>

</head>

<body>
    <!-- Header -->
    <header class="header" id="header">
        <!-- Navigation -->
        <div class="navigation">
            <nav class="nav__center container">
                <div class="nav__logo">
                    <span>
                        <svg>
                            <use xlink:href="{% static 'img/sprite.svg' %}#icon-map2"></use>
                        </svg>
                    </span>
                    <h1>WTK</h1>
                </div>

                <div class="nav__menu">
                    <ul class="nav__list">
                        <li class="nav__item">
                            <a href="{% url 'main:home' %}" class="nav__link special">Home</a>
                        </li>
                    </ul>
                </div>

                <div class="hamburger">
                    <svg>
                        <use xlink:href="{% static 'img/sprite.svg' %}#icon-menu"></use>
                    </svg>
                </div>
            </nav>
        </div>

        <br>
        <br>
        <br>


        <div class="container">
            <!-- Bar Chart - START -->
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <div id="chartContainer" style="height: 370px; width: 100%;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">

                                <form method="POST" action="{% url 'main:weight' %}">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {% if messages %}
                                        <ul class="messages" style="list-style-type: none;">
                                            {% for message in messages %}
                                            <li class="alert alert-danger">
                                                <strong>{{message}}</strong>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                        <strong><label for="text" style="font-weight: bolder;font-size: 20px;">Enter
                                                Weight
                                                data:</label></strong>
                                        <input type="number" name="weight" min="0" required id="id_weight"
                                            class="form-control input-lg form-rounded"
                                            style="height: 50px;font-size: medium;">
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-lg"
                                        style="font-size: 15px;">Submit</button>
                                </form>

                            </div>
                            <div id="chart2" class="panel-body">

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- you need to include the shieldui css and js assets in order for the charts to work -->
            <link rel="stylesheet" type="text/css"
                href="http://www.shieldui.com/shared/components/latest/css/light/all.min.css" />
            <script type="text/javascript"
                src="http://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>

            <script>
                const data = {{ data| safe}}
            </script>

            <script>
                window.onload = function () {

                    var options = {
                        animationEnabled: true,
                        title: {
                            text: "Bar chart visualization"
                        },
                        axisY: {
                            title: "Body Weight (in kg)",
                            suffix: "kg"
                        },
                        axisX: {
                            title: "Dates"
                        },
                        data: [{
                            type: "column",
                            yValueFormatString: "#,##0.0#" % "",
                            dataPoints: data
                        }]
                    };
                    $("#chartContainer").CanvasJSChart(options);

                }
            </script>
            <!-- Bar Chart - END -->

        </div>
        <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
        <script src="https://canvasjs.com/assets/script/jquery.canvasjs.min.js"></script>
        <script src="{% static 'js/index1.js' %}"></script>
    </header>
</body>

</html>

main/templates/main/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Google Font -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@400;600;700;800&display=swap" rel="stylesheet" />

    <!-- Custom Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style1.css' %}" />
    <title>WTK| HOME</title>
</head>

<body>
    <!-- Header -->
    <header class="header" id="header">
        <!-- Navigation -->
        <div class="navigation">
            <nav class="nav__center container">
                <div class="nav__logo">
                    <span>
                        <svg>
                            <use xlink:href="{% static 'img/sprite.svg' %}#icon-map2"></use>
                        </svg>
                    </span>
                    <h1>WTK</h1>
                </div>

                <div class="nav__menu">
                    <ul class="nav__list">
                        <li class="nav__item">
                            <a href="{% url 'main:home' %}" class="nav__link special">Home</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav__item">
                            <a href="{% url 'main:logout' %}" class="nav__link special">Log out</a>
                        </li>
                        <li class="nav__item">
                            <a href="{% url 'main:weight' %}" class="nav__link special">Activity</a>
                        </li>
                        {% else %}
                        <li class="nav__item">
                            <a href="{% url 'main:login' %}" class="nav__link  special">Log in</a>
                        </li>

                        <li class="nav__item">
                            <a href="{% url 'main:signup' %}" class="nav__link special">Sign up</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

                <div class="hamburger">
                    <svg>
                        <use xlink:href="{% static 'img/sprite.svg' %}#icon-menu"></use>
                    </svg>
                </div>
            </nav>
        </div>

        <!-- Banner -->
        <div class="banner container">

            <div class="banner__center">

                <div class="banner__left">
                    <span>

                        {% if messages %}
                        {% for message in messages %}
                        <ul>
                            <li class="alert alert-success">
                                <strong>{{message}}</strong>
                            </li>

                        </ul>
                        {% endfor %}
                        {% endif %}

                    </span><br><br><br>

                    <span><strong> Welcome{% if user.is_authenticated%}, {{ user.get_full_name}}
                            {% endif %}</strong></span>
                    <h1>Weight Tracker - WTK</h1>
                    <p>
                        WTK is a Weight Tracking application.It creates a visual representation
                        of your weight over time.This accessible application is
                        the perfect way to chart your weight loss. The visually stunning design is easy to read and
                        on the eyes.

                    </p>


                    <a href="{% url 'main:weight' %}">Get Started</a>
                </div>
                <div class="banner__right">
                    <img src="{% static 'img/pic.svg' %}" alt="" />
                </div>
            </div>
        </div>
    </header>
    <script src="{% static 'js/index1.js' %}"></script>
</body>

</html>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
    <title>Sign In and Sign Up Form</title>
</head>

<body>
    <div class="container">
        <div class="forms-container">
            <div class="signin-signup">
                <form action="" class="sign-in-form">
                    <h2 class="title">Sign in</h2>
                    <div class="input-field">
                        <i class="fas fa-user"></i>
                        <input type="text" placeholder="Username">
                    </div>
                    <div class="input-field">
                        <i class="fas fa-user"></i>
                        <input type="password" placeholder="Password">
                    </div>
                    <input type="submit" value="Login" class="btn solid">
                    <p class="social-text">Or Sign in with social platforms</p>
                    <div class="social-media">
                        <a href="#" class="social-icon">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a href="#" class="social-icon">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a href="#" class="social-icon">
                            <i class="fab fa-google"></i>
                        </a>
                        <a href="#" class="social-icon">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                    </div>
                </form>
            </div>
        </div>
        <div class="panels-container"></div>
    </div>
</body>

</html>

main/templates/main/signup_signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />

    <title>{% if request.path == "/login/" %}Login to Weight-Track{% else %}Sign up for
        Weight-Track{% endif %} </title>
</head>

<body>
    <div class="container">
        <div class="forms-container">
            <div class="signin-signup">
                <form action="{% url 'main:login' %}" class="sign-in-form" method="POST">
                    {% csrf_token %}

                    <h2 class="title">Sign in</h2>
                    {{form.non_field_errors }}

                    {{ form.source.errors }}
                    {{ form.source }}
                    <div class="input-field">

                        <i class="fas fa-envelope"></i>
                        {% if sign_in_form %}
                        {{ sign_in_form.email }}

                        {% else %}
                        {{form.email}}

                        {% endif %}
                    </div>
                    {% if request.path == "/login/" %}
                    {{form.email.errors }}
                    {% endif %}

                    <div class="input-field">
                        <i class="fas fa-lock"></i>
                        {% if sign_in_form %}
                        {{ sign_in_form.password }}
                        {% else %}
                        {{form.password}}
                        {% endif %}
                    </div>
                    {{form.password.errors }}
                    <input type="submit" value="Login" class="btn solid" />
                    <p class="social-text">Or Sign in with social platforms</p>
                    <div class="social-media">
                        <a href="#" class="social-icon">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a href="#" class="social-icon">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a href="#" class="social-icon">
                            <i class="fab fa-google"></i>
                        </a>
                        <a href="#" class="social-icon">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                    </div>
                </form>
                <form action="{% url 'main:signup' %}" class="sign-up-form" method="POST">
                    {% csrf_token %}

                    <h2 class="title">Sign up</h2>
                    <div class="input-field">
                        <i class="fas fa-user"></i>
                        {% if sign_up_form %}
                        {{ sign_up_form.first_name }}
                        {% else %}
                        {{form.first_name}}
                        {% endif %}
                    </div>
                    {{form.first_name.errors }}
                    <div class="input-field">
                        <i class="fas fa-user"></i>
                        {% if sign_up_form %}
                        {{ sign_up_form.last_name }}
                        {% else %}
                        {{form.last_name}}
                        {% endif %}
                    </div>
                    {{form.last_name.errors }}
                    <div class="input-field">
                        <i class="fas fa-envelope"></i>
                        {% if sign_up_form %}
                        {{ sign_up_form.email }}
                        {% else %}
                        {{form.email}}
                        {% endif %}
                    </div>
                    {% if request.path == "/signup/"  %}
                    {{form.email.errors }}
                    {% endif %}
                    <div class="input-field">
                        <i class="fas fa-lock"></i>
                        <input type="password" name="password1" autocomplete="new-password" required id="id_password1"
                            placeholder="Password" />
                    </div>
                    {{form.password1.errors }}
                    <div class="input-field">
                        <i class="fas fa-lock"></i>
                        <input type="password" name="password2" autocomplete="new-password" required id="id_password2"
                            placeholder="Confirm Password" />
                    </div>
                    {{form.password2.errors }}
                    <input type="submit" class="btn solid" value="Sign up" />
                    <p class="social-text">Or Sign up with social platforms</p>
                    <div class="social-media">
                        <a href="#" class="social-icon">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a href="#" class="social-icon">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a href="#" class="social-icon">
                            <i class="fab fa-google"></i>
                        </a>
                        <a href="#" class="social-icon">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                    </div>
                </form>
            </div>
        </div>

        <div class="panels-container">
            <div class="panel left-panel">
                <div class="content">
                    <h3>New here ?</h3>
                    <p>

                    </p>
                    <button class="btn transparent" id="sign-up-btn">
                        Sign up
                    </button>
                </div>
                <img src="{% static 'img/log.svg' %}" class="image" alt="" />
            </div>
            <div class="panel right-panel">
                <div class="content">
                    <h3>One of us ?</h3>
                    <p>

                    </p>
                    <button class="btn transparent" id="sign-in-btn">
                        Sign in
                    </button>
                </div>
                <img src="{% static 'img/register.svg' %}" class="image" alt="" />
            </div>
        </div>
    </div>

    <script>
        const path = {{ request.path }};

    </script>

    <script src="{% static 'js/app.js' %}"></script>
</body>

</html>